import { IGoalModel } from './types';

const mockData = [{
   userId: 1424,
   userDisplayName: "Abrie van Wyk",
   id: 12673,
   kraId: 1,
   kraTitle: "Product & Service Innovation",
   timing: "daily",
   weight: 10,
   priority: 1,
   createdTimestamp: new Date().getTime(),
   description: "Abrie EDIT ITEM 1 Lorem Ipsum - Goal Description",
   measureOfSuccess: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
   achievementCriteria: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
   batchId: 1109
},{
   userId: 1424,
   userDisplayName: "Abrie van Wyk",
   id: 2,
   kraId: 1,
   kraTitle: "Product & Service Innovation",
   // kraId: 2,
   // kraTitle: "People Development",
   timing: "weekly",
   weight: 20,
   priority: 2,
   createdTimestamp: new Date().getTime(),
   description: "Abrie ITEM 2 Lorem Ipsum - Goal Description",
   measureOfSuccess: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
   achievementCriteria: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
   batchId: 1109
},{
   userId: 1424,
   userDisplayName: "Abrie van Wyk",
   id: 3,
   // kraId: 1,
   // kraTitle: "Product & Service Innovation",
   kraId: 3,
   kraTitle: "Brand Equity",
   timing: "monthly",
   weight: 30,
   priority: 3,
   createdTimestamp: new Date().getTime(),
   description: "Abrie ITEM 3 Lorem Ipsum - Goal Description",
   measureOfSuccess: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
   achievementCriteria: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
   batchId: 1109
},{
   userId: 1424,
   userDisplayName: "Abrie van Wyk",
   id: 4,
   kraId: 4,
   kraTitle: "Business Growth & Development",
   timing: "monthly",
   weight: 40,
   priority: 4,
   createdTimestamp: new Date().getTime(),
   description: "Abrie ITEM 4 Lorem Ipsum - Goal Description",
   measureOfSuccess: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
   achievementCriteria: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
   batchId: 1109
},
{
   userId: 96,
   userDisplayName: "Jessica Alberts",
   id: 5,
   kraId: 1,
   kraTitle: "Product & Service Innovation",
   timing: "daily",
   weight: 10,
   priority: 1,
   createdTimestamp: new Date().getTime(),
   description: "Jessica ITEM 1 Lorem Ipsum - Goal Description",
   measureOfSuccess: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
   achievementCriteria: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
   batchId: 928
},{
   userId: 96,
   userDisplayName: "Jessica Alberts",
   id: 6,
   kraId: 2,
   kraTitle: "People Development",
   timing: "weekly",
   weight: 20,
   priority: 2,
   createdTimestamp: new Date().getTime(),
   description: "Jessica ITEM 2 Lorem Ipsum - Goal Description",
   measureOfSuccess: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
   achievementCriteria: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
   batchId: 928
},{
   userId: 96,
   userDisplayName: "Jessica Alberts",
   id: 7,
   kraId: 3,
   kraTitle: "Brand Equity",
   timing: "monthly",
   weight: 30,
   priority: 3,
   createdTimestamp: new Date().getTime(),
   description: "Jessica ITEM 3 Lorem Ipsum - Goal Description",
   measureOfSuccess: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
   achievementCriteria: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
   batchId: 928
},{
   userId: 96,
   userDisplayName: "Jessica Alberts",
   id: 8,
   kraId: 4,
   kraTitle: "Business Growth & Development",
   timing: "monthly",
   weight: 40,
   priority: 4,
   createdTimestamp: new Date().getTime(),
   description: "Jessica ITEM 4 Lorem Ipsum - Goal Description",
   measureOfSuccess: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
   achievementCriteria: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
   batchId: 928
}] as IGoalModel[];
export default mockData;
export const myGoalsMockData = mockData.filter(x => x.userId === 1424)